### ISSUE TITLE
bells or five-bells

### ISSUE THREAD

**Issue by vhpoet** [interledgerjs/ilp-kit-cli#1]
I've noticed a usage of `bells` instead of `five-bells` in the repo. Any particular reason? I think it would be less confusing to use `five-bells`.

**Comment by sharafian** [comment]
In `five-bells-connector`, the `type` in the auth field is used to create a Ledger Plugin by using `require('ilp-plugin-' + auth.type)`. The `type` field inside of the JSON has to stay as `bells` in order to import `ilp-plugin-bells`, but it would be possible to make the `--type` parameter use `five-bells` instead of `bells`, if you think that would be less confusing

**Comment by emschwartz** [comment]
The plugin could also be renamed `js-ilp-plugin-five-bells`
