### ISSUE TITLE
One secret for ILP kit

### ISSUE THREAD

**Issue by justmoon** [interledgerjs/ilp-kit-cli#14]
When setting up ILP kit, the CLI should ask for a secret.

This secret should be set in the config and ILP Kit should derive from it all other secrets when starting up. That includes the secrets for trustlines.

It's nice if it's still possible to pass a secret to the ilp-plugin-virtual options that overrides the connector-wide plugin secret. But since this is a very advanced use case, this shouldn't appear in the CLI.

**Comment by sharafian** [comment]
I think it would be the best if the plugin secret is drawn from the config when adding a peer, and then put in the plugin's configuration.

That means that if you peer with somebody, and then you change your secret, the trust-line will continue to function. If your old secret has been compromised, you can delete that trust-line and make a  new one. The `list` command could be modified in order to show which plugins use secrets that don't match your ILP Kit's secret.

The key command can be modified to use a file and then get the secret from that, instead of taking a secret as input.

This has the added bonus of requiring no changes in plugin virtual nor the connector.
