### ISSUE TITLE
Ask for hostname, not public key when peering

### ISSUE THREAD

**Issue by justmoon** [interledgerjs/ilp-kit-cli#15]
The CLI should ask for the peer's hostname and fetch the public key automatically.

It's nice if you can override the public key used in the plugin-virtual options, but this is an advanced use case and does not need to be supported by the CLI.

**Comment by sharafian** [comment]
Should plugin virtual be changed in order to get the public key from a hostname each time it connects? Is there currently an endpoint in the ILP Kit where the public key can be placed?

The options seem to be:

- CLI prompts for hostname, fetches pubkey, puts key in plugin-virtual configuration (peer must be running their ILP kit)
- CLI prompts for pubkey, puts key in plugin-virtual configuration (both parties can be offline)
- CLI prompts for hostname, puts hostname in plugin-virtual configuration (both plugin-virtuals must retry fetching the public key until the other is online, but configuration is offline)

**Comment by sharafian** [comment]
Added in verson 8.0.0

**Comment by justmoon** [comment]
Depends on interledgerjs/five-bells-ledger#101.

I think we should go with this option for now:

> CLI prompts for hostname, fetches pubkey, puts key in plugin-virtual configuration (peer must be running their ILP kit)

Reason being that we currently don't support changing tokens for various reasons:

* CONNECTOR_LEDGERS should be an array not a map. Right now the ILP prefix has to be mentioned in the config as the key of the CONNECTOR_LEDGERS object, when in reality it should be an optional parameter.
* Changing the public key changes the token, so we have to make sure that that doesn't cause the state to get reset. (Maybe it already doesn't because we explicitly set a database file, but need to verify.)
* `prefix` is currently hard-coded in the config (should be generated on the fly)
* `connector` is currently hard-coded in the config (should be generated on the fly)

**Comment by sharafian** [comment]
Resolved by the new peering flow
