### ISSUE TITLE
Clarify output option and next steps

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-kit-cli#4]
For the last question `Write these options to "connector.list"?` it's unclear what the alternative is.

Also, it might be good to print some kind of "next steps" at the end. I just ran configure, now what? How do I use the result of that step?

**Comment by emschwartz** [comment]
Two more things that could be clarified are why it asks you if you want to configure Mailgun and logging in with Github. It should explain what that's for, and what the alternative is if you say no

**Comment by sharafian** [comment]
I removed the confirmation to write to the file, because it just aborted the process if you said 'no'. I also [improved the help text for some of the confusing options.](https://github.com/interledgerjs/ilp-kit-cli/commit/f7fd331542a095722e15ada5f3a3b606428973cd) Let me know if there are any other questions that need clarification.
